version: '3.8'

services:
  telegram-bot:
    container_name: telegram-bot
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
    working_dir: /app
    command: python main.py